### PR TITLE
Update files for OpenCV4 / ROS Noetic

### PR DESCRIPTION
**Pull request by zthorson**

### CODE REVIEW

**Comment by zthorson** [comment]
I usually perform merge requests on the develop branch rather than master.  However in this case, master seems to be far ahead of dev.  Is this expected?  I can adjust it to merge to dev if you prefer.

**Comment by laxnpander** [comment]
@zthorson: This repo doesn’t get the love it deserves. Dev build should be ahead all the time, I will get this straight within the next days. I guess I will merge dev into master for both, the core library and the ros bridge. Then we have a clean state to start from. Wanted to do it for a while anyway :-)

**Review by laxnpander — COMMENTED** [review]
Some of the changes shouldn't be required anymore due to the merge with dev. The CGAL problem also occurred to me recently, however here is the wrong place to address it. It should come with the realm_ortho module. I will look into it!

**Comment by laxnpander** [comment]
Added most of this in https://github.com/laxnpander/OpenREALM_ROS1_Bridge/commit/88e2feed2f168f2b0ede37db1f657e584ca16790

**Pull request closed without merging**
